project:
  type: website
  output-dir: docs

website:
  title: "Oleksandra Smilyk"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

